name: PR sync handler
run-name: ${{github.event_name}}:${{github.event.action}} for PR ${{ github.event.number}} in ${{ github.repository }}
on:
  pull_request:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by ${{ github.event_name }}:${{ github.event.action}}"
      - run: echo "ğŸ”  This pull request was created at ${{ github.event.pull_request.created_at }}."
      - run: echo "ğŸ”  This pull request has github.event.pull_request.mergeable of ${{ github.event.pull_request.mergeable }}."
      - run: echo "ğŸ”  This pull request has github.event.mergeable of ${{ github.event.mergeable }}."
      - run: echo "ğŸ”  This pull request has github.pull_request.mergeable of ${{ github.pull_request.mergeable }}."
      - run: echo "ğŸ”  The base ref is ${{ github.base_ref }}."
      - run: echo "ğŸ”  The head ref is ${{ github.ref }}."
      - run: echo "ğŸ”  The head SHA is ${{ github.sha }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
